Month 9/step 1
Virshinia/react-burger pull request #5
Opened 2023-01-17 21:04 UTC by Virshinia

2023-01-17 21:55 UTC, andryxxa93 requested changes
Проделана большая работа! Роутинг настроен и работает правильно. Весь требуемый функционал работает корректно. Хочется отметить как здорово реализован `ProtectedRoute` с логикой для авторизованных и не авторизованных пользователей.

Есть только одно замечание - сейчас при ошибке 403 (протусхшем токене) не работает его обновление. Если access токен протух его надо обновить refresh токеном и повторить неудавшийся запрос с новым токеном. Воспроизвести эту ошибку можно так - авторизоваться, подождать 20 минут и попробовать изменить данные юзера. 

https://user-images.githubusercontent.com/60173362/213020825-f21651d0-9201-4a21-bb97-8bb8079aa112.mov


Удачи!

2023-01-26 10:11 UTC, andryxxa93 requested changes
Есть небольшая проблема - когда заходишь в приложение то происходит запрос данных пользователя, который получает 403 ошибку - потому что токена нет. После ошибки сразу вызывается обновление токена, которое так же не проходит, потому что refresh токена тоже пока что нет. И всё это зацикливается - из-за чего зарегистрироваться невозможно. 

https://user-images.githubusercontent.com/60173362/214809557-7e3af10b-0cdf-4a1a-a8c1-85a84b0f1be7.mov


И вторая проблема, что сейчас если всё-таки залогиниться и подождав 20 минут попробовать изменить данные пользователя, то токен обновляется, но в новый запрос на изменение данных всё равно попадает старый токен. 
1. Запрос с протухшим токеном. Обратите внимание на токен авторизации.
<img width="1439" alt="Снимок экрана 2023-01-26 в 13 05 51" src="https://user-images.githubusercontent.com/60173362/214809982-94d2b115-9a5d-4455-a952-c67d56f879e3.png">
2. Второй запрос на изменение данных уже после того как токен был успешно обновлен. Обратите внимание на токен авторизации, он такой же как и в первом запросе до обновления токена.
<img width="1440" alt="Снимок экрана 2023-01-26 в 13 08 28" src="https://user-images.githubusercontent.com/60173362/214810184-09a18f99-27f6-451b-9804-95ae207ae82c.png">

2023-01-26 10:11 UTC, andryxxa93 commented on src/components/total-cost/total-cost.jsx
> +  const {userIsAuthenticated} = useSelector(store => store.user);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-01-26 19:02 UTC, Virshinia commented on src/components/total-cost/total-cost.jsx
> +  const {userIsAuthenticated} = useSelector(store => store.user);
Ничего себе была "небольшая проблема". Очень даже большая. Пофиксила. в useSelector передала именованную функцию

2023-01-27 07:04 UTC, andryxxa93 approved these changes
Теперь всё отлично, вы очень хорошо потрудились! Успехов в дальнейшем обучении.

2023-01-27 07:05 UTC, andryxxa93 commented on src/components/total-cost/total-cost.jsx
> +  const {userIsAuthenticated} = useSelector(store => store.user);
Проблема небольшая в плане того, что её можно решить относительно малым количеством правок.

2023-01-27 21:43 UTC, merged