Month 9/step 2
Virshinia/react-burger pull request #6
Opened 2023-02-02 23:56 UTC by Virshinia

2023-02-03 04:25 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Есть страница Лента заказов;
- Есть страница История заказов;
- Используются webSockets;

### **Но есть несколько замечаний, которые нужно исправить:**

- Давайте оставим тут только 3 столбика, по 5 элементов, как это сделано в макете: <https://disk.yandex.com/i/cOWpOU0DAWH2CQ>;

- По чек-листу, если пользователь переходит на другую страницу с `/feed` или `/profile/orders`, то сокет соединение должно закрываться, а у вас оно продолжает работать) <https://disk.yandex.com/i/X2Msutfl2ACKuA>;

- Должна быть активна, только эта ссылка: <https://disk.yandex.com/i/phoXgoWjjW3PZw>;

- У вас почему-то не работает сокет соединение `/profile/orders`, хотя подключение вроде корректно (и ошибок нигде нет), но оно не работает :( ;

- на POST `/order`, вам нужно передавать в хедер 'authorization token' вот такого вида: <https://disk.yandex.com/i/-iPTVz2vqNxsXw>;

- В запросе POST `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/QAzg1Kh0pq96Xg>;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-03 04:25 UTC, ArslanDev666 commented on src/components/order-board/order-board.jsx
> +  const inProgress = orders.filter((order) => order.status !== "done");
**Можно лучше:** 

Лучше обернуть в useMemo

2023-02-03 04:25 UTC, ArslanDev666 commented on src/services/reducers/websocket.js
> +  currentOrder: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-02-03 21:20 UTC, Virshinia commented
1. Касательно столбиков. В макете просто показан пример. Поэтому там 1 столбик с 5 готовыми заказами и 1 стобик "в работе". В чеклисте указано:   _"Разделение между колонками
производится на основе значения поля status каждого заказа. Каждая из этих колонок содержит в себе не
более 10 записей, иначе — создаётся дополнительная колонка."_

Ссылка на чеклист: https://code.s3.yandex.net/web-plus/checklists/checklist_pdf/checklist_9-2.pdf

По количеству столбцов нет никакой конкретики, но я понимаю, что скрол может выглядеть не слишком красиво. Поэтому предлагаю оставить вариант с двумя столбцами по 10 записей.


2. Поправила закрытие сокета. Теперь закрывается.

3. Стиль с активными ссылками поправила.

3. Соединение с историей заказов у меня работает. Возможно нужно дать больше времени? И да, по какой-то причине он обычно очень долго отрабатывает.

4. Добавила токен в отправку заказа.

5. Добавила вторую булку в конец

2023-02-04 05:00 UTC, ArslanDev666 commented on src/services/reducers/websocket.js
> +      state.currentOrder = {};
Не забудьте тоже на null поменять)

2023-02-04 05:02 UTC, ArslanDev666 commented
Действительно, история заказов работает корректно)) может на тот момент что-то с бэком было.

2023-02-04 05:03 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

2023-02-05 06:04 UTC, merged